//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Producto_2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public int numeroHabitacion { get; set; }
        public Nullable<int> tipoHabitacion { get; set; }
        public string descripcion { get; set; }
        public int tipoID { get; set; }
        public string estado { get; set; }
        public Nullable<byte> fueraServicio { get; set; }
    }
}
