//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Producto_2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int idServicio { get; set; }
        public Nullable<double> precioServicio { get; set; }
        public string descripcion { get; set; }
        public int tipoServicioID { get; set; }
        public Nullable<double> precioAlta { get; set; }
        public Nullable<double> precioBaja { get; set; }
        public Nullable<double> precioMedia { get; set; }
        public Nullable<byte> permisoAlta { get; set; }
        public Nullable<byte> permisoMedia { get; set; }
        public Nullable<byte> permisoBaja { get; set; }
        public Nullable<double> descVIP { get; set; }
    }
}
